# -*- coding: utf-8 -*-
"""WEEK1-PYTHON.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XMUcaKfCAvDvMp9y70WKwDuFmDr9hMHF
"""

#1. Q: What is 7.3 plus 5+4j?
a=7.3
b=5+4j
c=a+b
print(c)

#1. Q Are 4e4 and 4E4 same? Check using a python operator.

print(4e4==4E4)

#1. Q  if c = 3 + 5j, store it’s real and imaginary parts into r and i variables
#respectively.
c=3+5j
a=c.real
b=c.imag
print("real part=",int(a))
print("imaginary part=",int(b))

#1. Q Call the euler’s number e and truncate the decimal part of the number and 
#store that into a variable.
import math
print(math.e)
a=math.e
print(math.trunc(a))

#2. Pass a dictionary into a function and print the elements of the dictionary.

d={"a":1,"b":3,"c":9}
def fn(d):
  return d
k=fn(d)
print(k)

#3. Print the factorial of a user input number.

N=int(input("n:"))
fact=1
i=N
while(i>=1):
  fact=fact*i
  i-=1
if i==0:
  print("factorial:",fact)

#4. Print a Fibonacci series upto the given number.

n=int(input("n:"))
prev=0
pres=1
print("Fibonacci Series:",prev)
while pres<=n:
  print(pres)
  next=prev+pres;
  prev=pres
  pres=next

#5. Given an array of integers,find the sum of positive and negative numbers
#separately and print "POSITIVE" if sum of positive numbers is greater than the
#absolute value of the sum of negative numbers, else print "NEGATIVE".

n = int(input("Enter number of elements : "))
print("Enter the numbers:")
intg=[]
i=1
while i<=n:
    g = int(input())
    intg.append(g) 
    i+=1
p=0
n=0

for i in intg:

    if i>=0:
        p+=i
    else:
        n+=i
  
print("Sum of Positive No.s:",p)  
print("Sum of Negative No.s:",n)  

if(p>=-n):
    print("POSITIVE")
else:
    print("NEGATIVE")

#6. Given a string, return a string of the same length where the vowels are in the first
#and the consonants are in the last. But the inner order of vowels and consonants
#should not change.

s= input()
 
vowels = None
consonants = None
s=s.lower()
for i in s:
    if i == 'a' or i == 'e' or i == 'i' or i == 'o' or i == 'u':
        if vowels == None:
            vowels=i
        else:
            vowels+=i
    else:
        if consonants == None:
            consonants=i
        else:
            consonants+=i
            

ans = vowels+consonants
print(ans)

#7. Write a code which returns the first m multiples of a natural number n,
# without using any loop.

X=int(input("Enter No.:"))
Y=int(input("Enter ,of multiples:"))
nos=(list(range(X,X*(Y+1),X)))
print("Multiples are:",*nos,sep='\n')